### ISSUE TITLE
Undefined table: 7 ERROR: relation "chado_stock" does not exist LINE 1:

### ISSUE THREAD

**Issue by a2htray** [tripal/mainlab_tripal#3]
![image](https://user-images.githubusercontent.com/12782530/34550723-1d1719fc-f14e-11e7-9f82-e7fd295dbc91.png)

![image](https://user-images.githubusercontent.com/12782530/34550732-29f9fc84-f14e-11e7-89f0-370c9bf9bf44.png)

`Notice: Undefined property: stdClass::$all_relationships in include() (line 22 of /var/www/html/sites/all/modules/mainlab_tripal/theme/cottongen/mainlab_organism_base.tpl.php).
Warning: key_exists() expects parameter 2 to be array, null given in include() (line 27 of /var/www/html/sites/all/modules/mainlab_tripal/theme/cottongen/mainlab_organism_base.tpl.php).
Warning: key_exists() expects parameter 2 to be array, null given in include() (line 32 of /var/www/html/sites/all/modules/mainlab_tripal/theme/cottongen/mainlab_organism_base.tpl.php).
Warning: key_exists() expects parameter 2 to be array, null given in include() (line 37 of /var/www/html/sites/all/modules/mainlab_tripal/theme/cottongen/mainlab_organism_base.tpl.php).
Warning: array_key_exists() expects parameter 2 to be array, null given in chado_expand_var() (line 753 of /var/www/html/sites/all/modules/tripal/tripal_core/api/tripal_core.chado_variables.api.inc).
PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "chado_stock" does not exist LINE 1: ...cvterm_id = type_id) AS type, (SELECT nid FROM chado_stoc... ^: SELECT count(*) FROM (SELECT uniquename, (SELECT name FROM chado.cvterm WHERE cvterm_id = type_id) AS type, (SELECT nid FROM chado_stock WHERE stock_id = stock.stock_id) AS nid FROM chado.stock WHERE organism_id = (SELECT organism_id FROM chado.organism WHERE genus = :genus AND species = :species) AND (type_id NOT IN (SELECT cvterm_id FROM chado.cvterm WHERE name IN ('sample', 'clone') AND cv_id = (SELECT cv_id FROM chado.cv WHERE name = 'MAIN') ) )) A; Array ( [:genus] => Citrus [:species] => sinensis ) in chado_query() (line 1538 of /var/www/html/sites/all/modules/tripal/tripal_core/api/tripal_core.chado_query.api.inc).`

**Comment by chunhuaicheng** [comment]
CottonGen template has some 'stock' information showing on the organism page. You'll need to enable the 'Tripal Stock' module which will create the 'chado_stock' table in the 'public' schema.
